language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .
  - pip install codecov
  - pip install pytest-cov

script:
  - pytest --cov=halerror tests/

after_success:
  - codecov
